add mail server check

diff --git a/loot b/loot
--- a/loot
+++ b/loot
@@ -1,17 +1,33 @@
 #!/bin/bash
 
+# *************************************************************
+# This function redirect the pipe input to STDERR.
+#
+# @param stream
+# @return string
+#
+function STDERR () {
+  cat - 1>&2
+}
+
+error_detected=false
+if [ -z $MAIL_SERVER ]; then
+    echo "Set a \$MAIL_SERVER or you can't loot." | STDERR
+    exit;
+fi
+
 if [ -z $LOOTER_NAME ]; then
-    echo "Set a \$LOOTER_NAME or you can't loot.";
+    echo "Set a \$LOOTER_NAME or you can't loot." | STDERR
     exit;
 fi
 
 if [ -z $LOOTER_EMAIL ]; then
-    echo "Set a \$LOOTER_EMAIL or you can't loot.";
+    echo "Set a \$LOOTER_EMAIL or you can't loot." | STDERR
     exit;
 fi
 
 if [ -z $LOOT_CONTROLLER_EMAIL ]; then
-    echo "Set a \$LOOT_CONTROLLER_EMAIL or you can't loot.";
+    echo "Set a \$LOOT_CONTROLLER_EMAIL or you can't loot." | STDERR
     exit;
 fi
 
